177 motion control create new differentialdrive class
cogip/mcu-firmware pull request #179
Opened 2024-12-05 12:19 UTC by mlecriva

The purpose of this interface is to define a common interface used by
platform engine in order to use any kind of drive controller (eg.
DifferentialDrive or HolonomicDrive)

The interface provides one method to set polar robot velocity.

COGIP robots are differential. So, implement the differential drive
controller in order to convert robot polar speed into speed ratio for
each motors.

The speed ratio is defined using the motor electrical information found
in the datasheet. This ratio reflect the percentage of nominal motor
voltage to apply in order to reach the velocity wanted.

2025-01-25 23:30 UTC, gdoffe requested changes

2025-01-25 23:30 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveController.hpp
> +        const double left_wheel_speed_mm_period = command.distance() - (command.angle() * parameters_.track_width_mm() / 2);
prefer `mm_per_period` than `mm_period`, more explicit.
same for other variables

2025-01-25 23:30 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +                                            loop_period_(loop_period) {};
I think for such long list of parameters, we should create an associated struct.

2025-01-25 23:30 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    void set_left_wheel_diameter(double wheel_diameter) { left_wheel_diameter_ = wheel_diameter; }
Do you think a wheel diameter could change ? :thinking:

2025-01-25 23:30 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    /// @brief Return left motor wheel diameter value in mm.
Do you think we could need wheel diameter outside of the object ?

2025-01-25 23:30 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    ///        This value is useful to convert linear velocity in mm/s to a speed ration between 0 to 100%.
s/ration/ratio/

2025-01-25 23:30 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    ///        This speed ratio need to by applied to the max motor voltage in order to get the voltage needed
s/by/be/

2025-01-25 23:30 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    ///        This value is useful to convert linear velocity in mm/s to a speed ration between 0 to 100%.
s/ration/ratio/

2025-01-25 23:30 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    ///        This speed ratio need to by applied to the max motor voltage in order to get the voltage needed
s/by/be/

2025-01-25 23:30 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    void set_track_width(double track_width) { track_width_ = track_width; }
Same here, do we need to dynamically change track width ?

2025-01-25 23:30 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    void set_loop_period(double period) { loop_period_ = period; }
Same here, do we need to dynamically change track width ?

2025-01-27 20:29 UTC, mlecriva commented on lib/utils/include/utils.hpp
> +inline double saturate(double x, double min, double max)
I didn't find clamp in etl. 

There is a `std::clamp` function available. Do you want this one from stdlib ?

2025-01-27 20:37 UTC, mlecriva commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    void set_loop_period(double period) { loop_period_ = period; }
It will be more probable for the odometer track width size but in case of the encoder mounted on the motor wheel, we can change it according to odometry calibration results too.

2025-01-27 20:37 UTC, mlecriva commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    void set_track_width(double track_width) { track_width_ = track_width; }
It will be more probable for the odometer track width size but in case of the encoder mounted on the motor wheel, we can change it according to odometry calibration results too.

2025-01-27 20:37 UTC, mlecriva commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    ///        This speed ratio need to by applied to the max motor voltage in order to get the voltage needed
done

2025-01-27 20:37 UTC, mlecriva commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    ///        This value is useful to convert linear velocity in mm/s to a speed ration between 0 to 100%.
done

2025-01-27 20:37 UTC, mlecriva commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    ///        This speed ratio need to by applied to the max motor voltage in order to get the voltage needed
done

2025-01-27 20:37 UTC, mlecriva commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    ///        This value is useful to convert linear velocity in mm/s to a speed ration between 0 to 100%.
done

2025-01-27 20:37 UTC, mlecriva commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    /// @brief Return left motor wheel diameter value in mm.
same

2025-01-27 20:37 UTC, mlecriva commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    void set_left_wheel_diameter(double wheel_diameter) { left_wheel_diameter_ = wheel_diameter; }
It will be more probable for the odometer wheel size but in case of the encoder mounted on the motor wheel, we can change it according to odometry calibration results too.

2025-01-27 20:37 UTC, mlecriva commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveController.hpp
> +        const double left_wheel_speed_mm_period = command.distance() - (command.angle() * parameters_.track_width_mm() / 2);
Fixed.

2025-01-27 20:37 UTC, mlecriva commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveController.hpp
> +#pragma once
Done

2025-01-27 20:37 UTC, mlecriva commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveController.hpp
> +#pragma once
Done

2025-01-27 20:37 UTC, mlecriva commented on motion_control/drive_controller/include/drive_controller/DriveControllerInterface.hpp
> +// Copyright (C) 2024 COGIP Robotics association <cogip35@gmail.com>
Done

2025-01-27 20:39 UTC, mlecriva commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +                                            loop_period_(loop_period) {};
I used the same layout as other parameters class.

I agree that this long list of parameters is not optimal be i'm afraid that adding a struct will create redundancy with the parameter class.

what do you think ?

2025-01-27 20:48 UTC, gdoffe commented on lib/utils/include/utils.hpp
> +inline double saturate(double x, double min, double max)
I mean `etl::clamp` :wink:

2025-01-27 20:50 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveController.hpp
> +        const double left_wheel_speed_mm_period = command.distance() - (command.angle() * parameters_.track_width_mm() / 2);
Nop, you did not apply to all variables, I see `left_wheel_speed_mm_s` for example.

2025-01-27 20:52 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +                                            loop_period_(loop_period) {};
Oh my bad, I did mismatch between parameters and the business class.

2025-01-27 20:53 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    void set_left_wheel_diameter(double wheel_diameter) { left_wheel_diameter_ = wheel_diameter; }
true and it could be useful to keep setters to keep firmware generic and being setup only by the RPi.

2025-01-27 20:53 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    /// @brief Return left motor wheel diameter value in mm.
same :)

2025-01-27 20:55 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    void set_loop_period(double period) { loop_period_ = period; }
true, same as previous comment

2025-01-27 20:55 UTC, gdoffe commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
> +    void set_track_width(double track_width) { track_width_ = track_width; }
true, same as previous comment

2025-01-27 21:00 UTC, mlecriva commented on motion_control/drive_controller/include/drive_controller/DifferentialDriveController.hpp
> +        const double left_wheel_speed_mm_period = command.distance() - (command.angle() * parameters_.track_width_mm() / 2);
Done

2025-01-27 21:06 UTC, gdoffe approved these changes
LGTM now ! Good job !

2025-01-27 21:06 UTC, merged