Gdo new avoidance
cogip/mcu-firmware pull request #39
Opened 2021-04-30 17:10 UTC by gdoffe

This PR refactors avoidance which was not working in its actual configuration due to:

- Obstacles are oriented according to sensor position. Obstacles were oriented by an hazardous supposition that the robot obstacle was oriented to rush on our robot. However it cannot be determined just with a relative distance sensor.
- Moreover as obstacle are polygons when the robot rotates on itself, the obstacle rotates too leading to crossing the avoidance path. The result is the robot oscillating in front of an obstacle.

As simulation PID parameters have been tuned for testing, also add a commit on this.

2021-05-07 21:45 UTC, gdoffe commented on lib/obstacles/include/obstacles.h
>      double angle;           /**< Orientation of the obstacle */
Nope :)

2021-05-07 21:47 UTC, gdoffe commented on platforms/cortex/include/platform.h
> +#define LIDAR_MINIMUN_INTENSITY             1000                    /**< Minimum intensity required to validate a Lidar distance */
It is more related to avoidance than to the robot.
Maybe we should create a new section then ?

2021-05-12 22:23 UTC, Kheprys reviewed
Interresting changes. I've made a quick review, i'll need more time to review it in a more detailed way.

2021-05-12 22:23 UTC, Kheprys commented on lib/collisions/collisions.c
> +inline double collisions_compute_ordonate(double slope, const pose_t *b)
'ordonate' doesn't mean anything, do you mean "ordinate" ?

2021-05-12 22:23 UTC, Kheprys commented on lib/collisions/include/collisions.h
> +double collisions_compute_ordonate(double slope, const pose_t *b);
Same "ordonate" doesn't mean anything, do you mean "ordinate" ?

2021-05-15 22:04 UTC, gdoffe commented
> **collisions module:** since it's a module, its public functions should have a module prefix.
> 
> **collisions/avoidance:** I don't like using the `pose_t` type everywhere.
> This type is for a robot position (ie X, Y and angle). In these modules, it's only 2D points, so `vector_t` should be more appropriate, but the name is far from perfect.
> 
> Some commits still need to be squashed, like the "[Fix](https://github.com/cogip/mcu-firmware/pull/39/commits/cd89d84279876fc0a1aa69284d8f20a45718e090)" commit, but I would also squash " [use circle](b3bd757da194a74c6df6e7d5ebca58815601cee6)" and "[add multi-forms obstacles](https://github.com/cogip/mcu-firmware/pull/39/commits/5b34835e331529cc009393fcd557e08430ca15da)" commits, since the second mostly modifies the former one, and makes review difficult.

done

2021-05-16 08:07 UTC, ecourtois requested changes
In [commit](https://github.com/cogip/mcu-firmware/pull/39/commits/da6739c83aa9e9705f33592de8fd4a7525f4796a) message:
- '**OBSTACLE_RECTANGLE**' type is based on new 'rectangle_t' type.
- not signed

In [commit](https://github.com/cogip/mcu-firmware/pull/39/commits/7c4c70237569a77432340812a635e78d17a9e1cc) message:
- "It also changes return types to better **suit** needs."
- Remove conflict comments

In [commit](https://github.com/cogip/mcu-firmware/pull/39/commits/fcf9b28cdf219585277bdd74c6b5153a9a5c992a) message:
- "Avoidance should not care about the **obstace** type."
- Remove conflict comments

2021-05-16 17:00 UTC, ecourtois approved these changes
LGTM!!!

2021-05-16 17:26 UTC, merged