cup2021
cogip/mcu-firmware pull request #44
Opened 2021-07-05 11:53 UTC by gdoffe

Various fixes and configurations, mainly on LIDAR and sd21 in preparation of 2021 french robotic cup

2021-07-05 18:10 UTC, ecourtois requested changes
- In commit message "[drivers: sd21: remove size](https://github.com/cogip/mcu-firmware/pull/44/commits/ab92244197227e5ea741d2e704e32a22c4a559af)":
"that are written"

- In commit message "[platforms: cortex: fix SPI SD card reader configuration](https://github.com/cogip/mcu-firmware/pull/44/commits/5b31148d2537f6fc17830b54ab68ddea9bf5efaa)":
Two empty lines before Signed-off

CI does not pass the coding rules check.

Nice PR by the way!

2021-07-05 19:24 UTC, Kheprys approved these changes
LGTM, maybe adding several assert() during init could be a good idea to avoid bad behavior

2021-07-05 19:24 UTC, Kheprys commented on platforms/cortex/platform.c
> +    }
Should add an assert() to check path object here. The path is loaded right after on line 283 and can lead to a pointer exception.

Maybe previous gpio_init() checks can be done with assert() too but I don't know if it's a good idea or not

2021-07-12 23:28 UTC, gdoffe commented
> * In commit message "[platforms: cortex: fix SPI SD card reader configuration](https://github.com/cogip/mcu-firmware/pull/44/commits/5b31148d2537f6fc17830b54ab68ddea9bf5efaa)":
>   Two empty lines before Signed-off

Strange :
![image](https://user-images.githubusercontent.com/1143438/125367960-86613e80-e379-11eb-8e9f-71b583076105.png)

2021-07-14 16:05 UTC, ecourtois requested changes
Just one extra space to remove and it's good!

2021-07-14 16:05 UTC, ecourtois commented on platforms/pf_test/platform.c
> +        puts("WARNING: GPIO_DEBUG_LED not initialized !");
Not fixed ;-)

2021-07-14 17:47 UTC, ecourtois approved these changes
LGTM!

2021-07-14 20:19 UTC, merged