Add UART and Protobuf Example
cogip/mcu-firmware pull request #49
Opened 2021-11-11 22:13 UTC by ecourtois

This PR only adds an example that shows the configuration and usage of a second UART,
and uses Protobuf (nanopb package) messages to exchange data over this UART.
A client written in Python is also provided.

2021-11-15 01:08 UTC, gdoffe requested changes

2021-11-15 01:08 UTC, gdoffe commented on examples/uart-nanopb/main.cpp
> +        ((uint8_t *)&msg_length)[msg_length_bytes_received++] = data;
Why is it called `msg_length` as it is a data buffer ??

2021-11-15 01:08 UTC, gdoffe commented on examples/uart-nanopb/main.cpp
> +    }
I understand nothing to this callback, can you please add some comments ?

2021-11-15 01:08 UTC, gdoffe commented on examples/uart-nanopb/main.cpp
> +static uint32_t msg_bytes_received = 0;
Add some comments here please, to know the difference between all these variables.

2021-11-27 18:41 UTC, ecourtois commented
Close this PR as nanopb as finally been replaced by EmbeddedProto.
See #51

2021-11-27 18:41 UTC, closed without merging