Add Protobuf communication through UART module
cogip/mcu-firmware pull request #50
Opened 2021-11-12 14:02 UTC by ecourtois

Add `sys/uartpb` module, a module providing a generic class to send and receive Protocol messages over UART port.

This PR also adds an example that shows usage of a second UART to send and receive messages.
A client written in Python is also provided.

2021-11-15 10:17 UTC, gdoffe requested changes

2021-11-15 10:17 UTC, gdoffe commented on sys/uartpb/include/uartpb/UartProtobuf.hpp
> +    InputMessageType message;
Noob question: as the template InputMessageType seems to be used only there. Could the template be defined for this function and not for the class ?

2021-11-15 10:17 UTC, gdoffe commented on sys/uartpb/uartpb.cpp
> +}
I would appreciate a sequence diagram, i'm geting a bit lost. :confused:

2021-11-15 10:17 UTC, gdoffe commented on .github/workflows/compilation.yml
> +        sudo apt-get install -qq build-essential gcc-multilib g++-multilib gcc-arm-none-eabi libnewlib-arm-none-eabi uncrustify protobuf-compiler
should be in a dedicated commit

2021-11-15 10:17 UTC, gdoffe commented on .gitignore
> +*_pb2.py
should be in a dedicated commit.

2021-11-15 10:17 UTC, gdoffe commented on examples/uartpb/Makefile
> +#BOARD ?= cogip-native
dead code

2021-11-15 10:17 UTC, gdoffe commented on examples/uartpb/README.md
> +# Overview
See my comments in temporary PR: https://github.com/cogip/mcu-firmware/pull/49

2021-11-27 18:41 UTC, ecourtois commented
Close this PR as nanopb as finally been replaced by EmbeddedProto.
See #51

2021-11-27 18:41 UTC, closed without merging